sudo: required
before_script:
  - npm install gulp
  - npm install phantomjs
  - npm install wrench
  - npm install gulp-util
  - npm install gulp-load-plugins
  - npm install gulp-connect
script: gulp test
