sudo: required

before_script:
  - echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - npm install
  # - npm install gulp
  - npm install phantomjs
  - bower install -f

script: gulp test

language: node_js
node_js:
    - "0.10"
